export const PAGE_INDEX = {
    OPENING: 0,
    FINALLY_ASLEEP: 1,
    MORNING: 2,
    BOSS: 3,
    WORK: 4,
    KAREN_CALL: 5,
    SOCIAL_CIRCLE: 6,
    FIGHT: 7,
    DINNER: 8,
    LOST: 9,
    EXPLAIN: 10,
    JOHN_CALL: 11,
    RESOLUTION: 12,
    REVEAL: 13,
    ANGRY: 14,
};